import 'dotenv/config';
import express from 'express';
import { createServer as createViteServer } from 'vite';
import { aiInsight, performance, portfolioFor, strategies, transactions, vaults } from './mockData.js';
import { getLiveSnapshot } from './simulation.js';
const port=Number(process.env.PORT||3000); const app=express(); app.use(express.json());
app.get('/api/health',(_q,r)=>r.json({ok:true,service:'boofy-alphabank',version:'0.7.0',mode:process.env.ALPHABANK_NETWORK||'demo-live'}));
app.get('/api/vaults',(_q,r)=>{const s=getLiveSnapshot();r.json(vaults.map((v,i)=>i? v:{...v,tvlUsd:s.tvlUsd,realizedUsdt:s.realizedUsdt,realizedYield:s.realizedYield}))});
app.get('/api/strategies',(_q,r)=>r.json(strategies)); app.get('/api/transactions',(_q,r)=>{const live=getLiveSnapshot().events;r.json([...live,...transactions].slice(0,12))}); app.get('/api/performance',(_q,r)=>r.json(getLiveSnapshot().performance));
app.get('/api/ai/insight',(_q,r)=>{const s=getLiveSnapshot();r.json({...aiInsight,riskScore:s.riskScore,headline:`${s.riskBand} Risk — live demo policy response`,summary:`Simulation tick ${s.tick}. Principal, realized profit and risk are recalculated from one coherent demo state.`})});
app.get('/api/portfolio/:wallet',(q,r)=>r.json({...getLiveSnapshot().portfolio,wallet:q.params.wallet}));
app.get('/api/live',(_q,r)=>r.json(getLiveSnapshot()));
app.get('/api/live/stream',(req,res)=>{res.setHeader('Content-Type','text/event-stream');res.setHeader('Cache-Control','no-cache');res.setHeader('Connection','keep-alive');res.flushHeaders();const send=()=>res.write(`data: ${JSON.stringify(getLiveSnapshot())}\n\n`);send();const timer=setInterval(send,2000);req.on('close',()=>clearInterval(timer))});
app.get('/api/system',(_q,r)=>r.json({api:['/api/health','/api/vaults','/api/strategies','/api/portfolio/:wallet','/api/performance','/api/transactions','/api/ai/insight','/api/ai/analyze','/api/live','/api/live/stream'],contracts:['AlphaBankVault.sol','AlphaProfitEngine.sol','IAlphaStrategy.sol','IAlphaSwapAdapter.sol'],integrations:{rpc:process.env.ALPHABANK_RPC_URL?'configured':'not-configured',vaultAddress:process.env.ALPHABANK_VAULT_ADDRESS?'configured':'not-configured',aiProvider:process.env.OPENAI_API_KEY?'configured':'demo-policy'}}));
app.post('/api/ai/analyze',(q,r)=>{const s=getLiveSnapshot(),pref=q.body?.riskPreference??'balanced';r.json({...aiInsight,riskScore:s.riskScore,headline:`${s.riskBand} Risk — ${pref} live-demo analysis`,stance:pref==='conservative'?'Conservative':pref==='opportunistic'?'Opportunistic':'Balanced',summary:`Live simulation tick ${s.tick}: principal ${s.portfolio.principalUsd.toFixed(2)} USD, claimable ${s.portfolio.claimableUsdt.toFixed(2)} USDT. Advisory output only.`,generatedAt:new Date().toISOString(),mode:'demo-live',disclaimer:'Simulation/research output only. No transaction is signed or submitted by the AI layer.'})});
app.use('/api',(_q,r)=>r.status(404).json({ok:false,error:'API route not found'})); const vite=await createViteServer({configFile:new URL('../../vite.config.ts',import.meta.url).pathname,server:{middlewareMode:true},appType:'spa'});app.use(vite.middlewares);app.listen(port,()=>{console.log(`\n  Boofy AlphaBank V7 Live Demo → http://localhost:${port}`);console.log(`  Live stream                → http://localhost:${port}/api/live/stream\n`)})
