import {
  Activity, ArrowDownToLine, ArrowRight, ArrowUpRight, BadgeDollarSign, Banknote,
  BarChart3, BellRing, BrainCircuit, CircleDollarSign, Clock3, Coins, Database,
  Gauge, KeyRound, Layers3, LockKeyhole, Network, Orbit, RefreshCw, Repeat2,
  Search, Settings2, ShieldCheck, SlidersHorizontal, Sparkles, TrendingDown,
  TrendingUp, UserRoundCog, Wallet, WalletCards, Zap
} from 'lucide-react';
import type { AiInsight, PortfolioSummary, StrategySummary, SystemStatus, TransactionSummary, VaultSummary } from '../../../src/shared/types';
import { PerformanceChart } from './PerformanceChart';

const money=(v:number,d=2)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',minimumFractionDigits:d,maximumFractionDigits:d}).format(v);

type Props={
  vaults:VaultSummary[]; strategies:StrategySummary[]; transactions:TransactionSummary[]; insight:AiInsight|null;
  portfolio:PortfolioSummary|null; performance:Array<{day:string;principal:number;realized:number}>; system:SystemStatus|null;
  wallet:string; setWallet:(v:string)=>void; lookup:()=>void; runAi:()=>void; aiLoading:boolean;
};

export function DashboardPage(p:Props){
 const tvl=p.vaults.reduce((a,v)=>a+v.tvlUsd,0)||1_248_320; const realized=p.vaults.reduce((a,v)=>a+v.realizedUsdt,0)||230_421; const y=p.vaults[0]?.realizedYield??18.6;
 return <div className="page-stack">
  <section className="page-hero dashboard-hero"><div><span className="eyebrow">ALPHABANK CONTROL CENTER</span><h1>See principal, realized profit and risk <em>together.</em></h1><p>One view for staking exposure, stablecoin realization and AI-assisted portfolio intelligence.</p></div><div className="hero-orbit"><Orbit/><span>Research MVP</span><strong>System online</strong></div></section>
  <section className="kpi-grid">
   <Kpi icon={<Database/>} label="Total Value Locked" value={money(tvl,0)} delta="+12.4%" />
   <Kpi icon={<Wallet/>} label="Demo Users" value="1,582" delta="+8.1%" />
   <Kpi icon={<CircleDollarSign/>} label="Realized USDT" value={money(realized,0)} delta="+15.7%" tone="green"/>
   <Kpi icon={<BarChart3/>} label="Realized Yield" value={`${y.toFixed(1)}%`} delta="+3.2%" />
  </section>
  <section className="two-col">
   <article className="panel premium-panel"><PanelHead icon={<WalletCards/>} title="Your Portfolio" action={<button onClick={p.lookup}><RefreshCw size={14}/> Refresh</button>}/><PortfolioMini portfolio={p.portfolio}/><div className="lookup-row"><input value={p.wallet} onChange={e=>p.setWallet(e.target.value)} placeholder="Wallet address"/><button onClick={p.lookup}>Analyze wallet</button></div></article>
   <article className="panel premium-panel"><PanelHead icon={<Layers3/>} title="AlphaBank Flow"/><div className="process-grid">{[['1','Stake','Allocate principal'],['2','Harvest','Collect rewards'],['3','Realize','Convert to USDT'],['4','Intelligence','Analyze risk']].map((x,i)=><div className="process-card" key={x[0]}><span className={`process-num n${i+1}`}>{x[0]}</span><strong>{x[1]}</strong><small>{x[2]}</small>{i<3&&<ArrowRight/>}</div>)}</div></article>
  </section>
  <section className="two-col lower"><article className="panel premium-panel"><PanelHead icon={<TrendingUp/>} title="Performance Overview"/><PerformanceChart points={p.performance}/><div className="chart-legend"><span><i className="blue-dot"/>Principal index</span><span><i className="green-dot"/>Realized USDT index</span></div></article><AiPanel insight={p.insight} runAi={p.runAi} loading={p.aiLoading}/></section>
 </div>
}

export function StakingPage(p:Props){return <div className="page-stack"><PageIntro kicker="STAKING" title="Put capital to work with transparent strategy boundaries." text="Principal stays visible while rewards are harvested into a separate profit ledger." icon={<Layers3/>}/><section className="feature-strip"><Feature icon={<Coins/>} title="Deposit asset" value="TOKEN" sub="Demo staking asset"/><Feature icon={<Gauge/>} title="Estimated staking APY" value="18.42%" sub="Illustrative only"/><Feature icon={<Clock3/>} title="Harvest cadence" value="48h" sub="Policy target"/><Feature icon={<ShieldCheck/>} title="Risk band" value="Moderate" sub="Current policy"/></section><section className="two-col"><article className="panel premium-panel action-panel"><PanelHead icon={<ArrowDownToLine/>} title="Stake into Alpha Vault"/><div className="balance-row"><span>Available demo balance</span><strong>12,500 TOKEN</strong></div><label>Amount to stake<div className="input-shell"><input defaultValue="5,000"/><button>MAX</button></div></label><div className="route-box"><div><small>Vault</small><strong>Alpha Staking Vault</strong></div><ArrowRight/><div><small>Settlement</small><strong>USDT Profit Bank</strong></div></div><button className="cta-wide">Preview Stake <ArrowRight/></button><p className="microcopy">Demo only. No wallet transaction is signed in this prototype.</p></article><article className="panel premium-panel"><PanelHead icon={<Activity/>} title="Position Health"/><PortfolioMini portfolio={p.portfolio}/><div className="health-list"><Health label="Principal utilization" value="96.8%"/><Health label="Reward realization ratio" value="72.4%"/><Health label="Slippage guard" value="0.50% max"/><Health label="Emergency status" value="Normal"/></div></article></section><section className="panel premium-panel"><PanelHead icon={<BellRing/>} title="Staking policy timeline"/><div className="timeline">{[['Deposit','Principal enters strategy adapter'],['Accrue','Rewards accumulate off principal ledger'],['Harvest','Keeper or approved actor collects rewards'],['Realize','Profit engine swaps approved rewards to USDT']].map((x,i)=><div key={x[0]}><span>{i+1}</span><strong>{x[0]}</strong><p>{x[1]}</p></div>)}</div></section></div>}

export function BankPage(p:Props){const pf=p.portfolio; return <div className="page-stack"><PageIntro kicker="USDT BANK" title="Turn token rewards into visible, claimable stablecoin profit." text="The reserve ledger separates realized USDT from volatile principal so users can see what was actually secured." icon={<Banknote/>}/><section className="bank-balance panel premium-panel"><div><small>USDT Bank Balance</small><strong>{money((pf?.realizedUsdt??348.21)+(pf?.claimableUsdt??48.12))}</strong><span>Total realized + claimable</span></div><div className="bank-orb"><CircleDollarSign/><span>USDT</span></div><div><small>Claimable now</small><strong>{money(pf?.claimableUsdt??48.12)}</strong><button>Claim demo USDT</button></div></section><section className="three-col"><article className="panel mini-panel"><BadgeDollarSign/><small>Realized profit</small><strong>{money(pf?.realizedUsdt??348.21)}</strong><span className="good">Secured from rewards</span></article><article className="panel mini-panel"><Repeat2/><small>Reinvestment allocation</small><strong>27.6%</strong><span>Policy-controlled</span></article><article className="panel mini-panel"><LockKeyhole/><small>Reserve protection</small><strong>Guarded</strong><span>Separate profit ledger</span></article></section><section className="two-col"><article className="panel premium-panel"><PanelHead icon={<TrendingUp/>} title="Profit realization path"/><div className="waterfall"><div><span>Reward earned</span><strong>412.70 RWD</strong></div><ArrowRight/><div><span>Realized share</span><strong>72.4%</strong></div><ArrowRight/><div><span>USDT secured</span><strong>$348.21</strong></div></div><div className="progress-block"><label>USDT realization progress <b>72%</b></label><div><i style={{width:'72%'}}/></div></div></article><article className="panel premium-panel"><PanelHead icon={<ShieldCheck/>} title="Reserve rules"/><div className="rule-list"><Rule title="No principal mixing" text="Realized USDT is accounted separately from staking principal."/><Rule title="Explicit claim ledger" text="Claimable and claimed balances remain visible to the portfolio layer."/><Rule title="Stablecoin is not principal protection" text="A falling staking asset can still outweigh realized yield."/></div></article></section></div>}

export function StrategiesPage(p:Props){return <div className="page-stack"><PageIntro kicker="STRATEGIES" title="A modular strategy layer built for controlled integrations." text="Each strategy exposes a narrow interface so staking, harvest and withdrawal logic stay auditable." icon={<TrendingUp/>}/><section className="strategy-grid">{p.strategies.map((s,i)=><article className="strategy-card" key={s.id}><div className="strategy-top"><span className={`strategy-icon c${i+1}`}><Zap/></span><span className="status-pill">{s.status}</span></div><small>{s.asset} → {s.settlement}</small><h3>{s.name}</h3><p>{s.harvestPolicy}</p><div className="strategy-stats"><div><small>Risk</small><strong>{s.risk}</strong></div><div><small>Automation</small><strong>{i?'Accounting':'Harvest'}</strong></div><div><small>Mode</small><strong>Research</strong></div></div><button>Inspect strategy <ArrowUpRight/></button></article>)}</section><section className="panel premium-panel"><PanelHead icon={<Network/>} title="Integration pipeline"/><div className="integration-pipeline">{['Vault interface','Protocol adapter','Reward collector','Approved DEX adapter','USDT reserve'].map((x,i)=><div key={x}><span>{i+1}</span><strong>{x}</strong>{i<4&&<ArrowRight/>}</div>)}</div></section></div>}

export function IntelligencePage(p:Props){return <div className="page-stack"><PageIntro kicker="ALPHA INTELLIGENCE" title="AI explains risk. Deterministic rules control execution." text="The intelligence layer combines portfolio state, market conditions and policy thresholds without receiving unrestricted signing authority." icon={<BrainCircuit/>}/><section className="intelligence-layout"><AiPanel insight={p.insight} runAi={p.runAi} loading={p.aiLoading}/><article className="panel premium-panel signal-panel"><PanelHead icon={<Sparkles/>} title="Signal Matrix"/><Signal label="Reward realization" score={84} note="Favors harvesting"/><Signal label="Principal drawdown" score={42} note="Within policy range"/><Signal label="Volatility pressure" score={58} note="Moderate"/><Signal label="Liquidity quality" score={79} note="Healthy demo depth"/></article></section><section className="three-col"><InsightCard icon={<BrainCircuit/>} title="Explain" text="Translate portfolio and strategy state into concise risk reasoning."/><InsightCard icon={<SlidersHorizontal/>} title="Recommend" text="Suggest harvest, realize or hold posture under explicit constraints."/><InsightCard icon={<ShieldCheck/>} title="Guard" text="Keep signing, permissions and on-chain execution outside the AI model."/></section><section className="panel premium-panel"><PanelHead icon={<Activity/>} title="Decision trace"/><div className="decision-trace"><div><span>01</span><strong>Observe</strong><p>Portfolio + vault + market inputs</p></div><ArrowRight/><div><span>02</span><strong>Evaluate</strong><p>Policy thresholds + AI explanation</p></div><ArrowRight/><div><span>03</span><strong>Validate</strong><p>Deterministic risk and slippage rules</p></div><ArrowRight/><div><span>04</span><strong>Execute</strong><p>User / keeper controlled transaction</p></div></div></section></div>}

export function PortfolioPage(p:Props){return <div className="page-stack"><PageIntro kicker="PORTFOLIO" title="Measure what you deposited, what remains and what you actually realized." text="AlphaBank keeps principal performance and stablecoin profit visible as separate but related ledgers." icon={<WalletCards/>}/><section className="panel premium-panel portfolio-hero"><div><small>Net P&L</small><strong className={(p.portfolio?.netPnlUsd??0)>=0?'good':'bad'}>{money(p.portfolio?.netPnlUsd??220.33)}</strong><span>{p.portfolio?.netPnlPct??4.4}% since deposit</span></div><div className="portfolio-ring"><span>{p.portfolio?.netPnlPct??4.4}%</span><small>NET RETURN</small></div><div className="lookup-row compact"><input value={p.wallet} onChange={e=>p.setWallet(e.target.value)}/><button onClick={p.lookup}><Search/>Analyze</button></div></section><section className="four-col"><MiniStat title="Deposited" value={money(p.portfolio?.depositedUsd??5000)}/><MiniStat title="Current principal" value={money(p.portfolio?.principalUsd??4872.3)}/><MiniStat title="Realized USDT" value={money(p.portfolio?.realizedUsdt??348.21)}/><MiniStat title="Claimable USDT" value={money(p.portfolio?.claimableUsdt??48.12)}/></section><section className="two-col"><article className="panel premium-panel"><PanelHead icon={<BarChart3/>} title="Value history"/><PerformanceChart points={p.performance}/></article><article className="panel premium-panel"><PanelHead icon={<Gauge/>} title="Exposure breakdown"/><div className="donut-wrap"><div className="css-donut"><span>100%</span></div><div className="legend-list"><div><i className="l1"/><span>Principal exposure</span><strong>79%</strong></div><div><i className="l2"/><span>Realized USDT</span><strong>17%</strong></div><div><i className="l3"/><span>Claimable USDT</span><strong>4%</strong></div></div></div></article></section></div>}

export function TransactionsPage(p:Props){return <div className="page-stack"><PageIntro kicker="TRANSACTIONS" title="Every movement should explain what happened to principal and profit." text="A unified activity view for deposits, harvests, realizations and claims." icon={<Activity/>}/><section className="panel premium-panel"><div className="table-toolbar"><div><Search/><input placeholder="Search activity"/></div><button><SlidersHorizontal/>Filter</button></div><div className="tx-table"><div className="tx-head"><span>Activity</span><span>Asset</span><span>Amount</span><span>Status</span><span>Time</span></div>{p.transactions.map((tx,i)=><div className="tx-row" key={tx.id}><span><i className={`tx-icon t${i%4}`}><TxIcon type={tx.type}/></i><b>{tx.type}</b><small>{tx.id}</small></span><span>{tx.asset}</span><strong>{tx.amount}</strong><span><i className="status-dot"/>{tx.status}</span><time>{new Date(tx.timestamp).toLocaleString()}</time></div>)}</div></section><section className="three-col"><InsightCard icon={<ArrowDownToLine/>} title="Deposits" text="Principal entering the AlphaBank vault."/><InsightCard icon={<Repeat2/>} title="Harvest + Realize" text="Reward collection and conversion to USDT."/><InsightCard icon={<ArrowUpRight/>} title="Claims" text="Stablecoin profit leaving the claim ledger."/></section></div>}

export function SettingsPage(p:Props){return <div className="page-stack"><PageIntro kicker="SETTINGS" title="Developer-ready controls for a research-stage DeFi system." text="Configuration is explicit, integrations are visible, and production assumptions are not hidden." icon={<Settings2/>}/><section className="two-col"><article className="panel premium-panel"><PanelHead icon={<Network/>} title="Integration Status"/><div className="setting-list"><Setting name="Blockchain RPC" value={p.system?.integrations.rpc??'not-configured'}/><Setting name="Vault address" value={p.system?.integrations.vaultAddress??'not-configured'}/><Setting name="AI provider" value={p.system?.integrations.aiProvider??'demo-policy'}/><Setting name="Runtime mode" value="demo"/></div></article><article className="panel premium-panel"><PanelHead icon={<ShieldCheck/>} title="Safety Controls"/><div className="toggle-list"><Toggle label="Transaction simulation" on/><Toggle label="AI advisory only" on/><Toggle label="Production signing" on={false}/><Toggle label="Mainnet mode" on={false}/></div></article></section><section className="two-col"><article className="panel premium-panel"><PanelHead icon={<KeyRound/>} title="Environment variables"/><pre className="env-code">PORT=3000{`\n`}ALPHABANK_NETWORK=demo{`\n`}ALPHABANK_RPC_URL={`\n`}ALPHABANK_VAULT_ADDRESS={`\n`}OPENAI_API_KEY=</pre></article><article className="panel premium-panel"><PanelHead icon={<UserRoundCog/>} title="Developer Handoff"/><div className="handoff-copy"><p>Replace demo providers behind existing API contracts instead of rewriting the UI.</p><ul><li>Connect viem RPC provider</li><li>Index vault and profit-engine events</li><li>Replace policy AI endpoint with approved model provider</li><li>Add real wallet connection</li><li>Run contract tests before any deployment</li></ul></div></article></section></div>}

function PageIntro({kicker,title,text,icon}:{kicker:string;title:string;text:string;icon:React.ReactNode}){return <section className="page-intro"><div><span className="eyebrow">{kicker}</span><h1>{title}</h1><p>{text}</p></div><div className="intro-icon">{icon}</div></section>}
function PanelHead({icon,title,action}:{icon:React.ReactNode;title:string;action?:React.ReactNode}){return <div className="panel-title"><h3>{icon}{title}</h3>{action}</div>}
function Kpi({icon,label,value,delta,tone}:{icon:React.ReactNode;label:string;value:string;delta:string;tone?:string}){return <article className="kpi-card"><span className={`kpi-icon ${tone??''}`}>{icon}</span><div><small>{label}</small><strong>{value}</strong></div><b>{delta}</b></article>}
function PortfolioMini({portfolio}:{portfolio:PortfolioSummary|null}){return <><div className="portfolio-stats"><div><small>Deposited</small><strong>{money(portfolio?.depositedUsd??5000)}</strong></div><div><small>Principal</small><strong>{money(portfolio?.principalUsd??4872.30)}</strong></div><div><small>Realized USDT</small><strong>{money(portfolio?.realizedUsdt??348.21)}</strong></div><div><small>Claimable</small><strong>{money(portfolio?.claimableUsdt??48.12)}</strong></div></div><div className="pnl-strip"><div><small>Net P&L</small><strong>▲ {money(portfolio?.netPnlUsd??220.33)}</strong></div><div><b>+{portfolio?.netPnlPct??4.4}%</b><small>Since deposit</small></div></div></>}
function AiPanel({insight,runAi,loading}:{insight:AiInsight|null;runAi:()=>void;loading:boolean}){return <article className="panel premium-panel ai-panel"><PanelHead icon={<BrainCircuit/>} title="AI Intelligence" action={<button onClick={runAi} disabled={loading}>{loading?'Analyzing…':'Run Analysis →'}</button>}/><div className="ai-score-row"><div className="risk-ring"><div><strong>{insight?.riskScore??72}</strong><span>/100</span></div></div><div><span className="eyebrow">CURRENT POSTURE</span><h3>{insight?.headline??'Moderate Risk'}</h3><p>{insight?.summary}</p></div></div><div className="factor-list">{(insight?.factors??[]).map((f,i)=><div key={f}><span>{i+1}</span><p>{f}</p></div>)}</div></article>}
function Feature({icon,title,value,sub}:{icon:React.ReactNode;title:string;value:string;sub:string}){return <article className="feature-tile"><span>{icon}</span><small>{title}</small><strong>{value}</strong><p>{sub}</p></article>}
function Health({label,value}:{label:string;value:string}){return <div><span>{label}</span><strong>{value}</strong></div>}
function Rule({title,text}:{title:string;text:string}){return <div><ShieldCheck/><span><strong>{title}</strong><p>{text}</p></span></div>}
function InsightCard({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <article className="panel insight-card">{icon}<h3>{title}</h3><p>{text}</p></article>}
function Signal({label,score,note}:{label:string;score:number;note:string}){return <div className="signal-row"><div><span>{label}</span><small>{note}</small></div><div className="signal-bar"><i style={{width:`${score}%`}}/></div><strong>{score}</strong></div>}
function MiniStat({title,value}:{title:string;value:string}){return <article className="panel mini-stat"><small>{title}</small><strong>{value}</strong><span>AlphaBank ledger</span></article>}
function TxIcon({type}:{type:string}){if(type==='Deposit')return <ArrowDownToLine/>;if(type==='Harvest')return <Zap/>;if(type==='Realize')return <Repeat2/>;return <ArrowUpRight/>}
function Setting({name,value}:{name:string;value:string}){return <div><span>{name}</span><strong className={value==='configured'?'good':''}>{value}</strong></div>}
function Toggle({label,on}:{label:string;on:boolean}){return <div><span>{label}</span><i className={on?'toggle on':'toggle'}><b/></i></div>}
